### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [jen-jen-jen/prj-rev-bwfs-dasmoto#4]
Grade: Exceeds Expectations

This is a fantastic take on the assignment. Your code is very digestible and concise, and your CSS techniques are spot on. You have all the necessary components and you've been deliberate in how you apply CSS classes to HTML elements. Awesome!

Moving forward, I'd start incorporating commenting into your code. As projects get bigger and more complex, comments inform collaborators what each block of code does, so it's never to early to start building that habit. Also, you might be interested in a few CSS resources that can enhance the design of your apps. Google Fonts has a bunch of interesting fonts to use, and Coolors.co generates color palettes that give your apps individuality. Just some thoughts! Again, great job!

**Comment by jen-jen-jen** [comment]
Thanks for the feedback!
